name: pysidt_env
channels:
  - defaults
  - conda-forge
  - mjohnson541
  - rmg
dependencies:
  - python >=3.7,<3.10
  - jupyter
  - nose
  - numpy
  - pydot
  - mjohnson541::rmgmolecule >=0.3.0
  - scikit-learn
  - scipy
  
